# Generated by Django 5.1.7 on 2025-04-07 17:17

import django.db.models.deletion
import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('name', models.CharField(default='Название номера', max_length=100, verbose_name='Название номера')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за комнату')),
                ('capacity', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('amenities', models.CharField(blank=True, max_length=250, verbose_name='Удобства')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность бронирования')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.roomcategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hotel.models.room_image_upload_path, verbose_name='Изображение')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.room')),
            ],
        ),
    ]
