# Generated by Django 5.1.7 on 2025-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_amenities_room_capacity_room_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Название номера', max_length=100, verbose_name='Название номера'),
        ),
    ]
