# Generated by Django 5.1.7 on 2025-04-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_roomcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='image',
        ),
    ]
