# Generated by Django 5.1.7 on 2025-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для бронирования'),
        ),
    ]
