# Generated by Django 5.1.7 on 2025-04-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='Имя неизвестно', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='Не указано', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='Номер не указан', max_length=13),
            preserve_default=False,
        ),
    ]
