# Generated by Django 5.1.7 on 2025-03-23 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
