# Generated by Django 5.1.7 on 2025-03-23 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250323_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancel_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
